# Generated by Django 5.0.3 on 2024-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='live_site_url',
            field=models.CharField(default='empty', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_code_url',
            field=models.CharField(default='empty', max_length=400),
            preserve_default=False,
        ),
    ]
